name: Publish for argocd

on:
  push:
    branches:
      - main
      - Feature/Deployment
    paths:
      - src/**
      - pom.xml
      - .github/workflows/publish.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SERVER_PORT: 8081
      DB_HOST: localhost
      DB_PORT: 5433
      DB_NAME: test_db
      DB_USERNAME: test_user
      DB_PASSWORD: test_password

    permissions:
      contents: read

    steps:

      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      # Install Java
      - name: Setup JDK 17
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Cache Sonar packages
      - name: Cache Sonar Packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

        # Build the project
      - name: Build with Maven
        run:  mvn -B clean verify

      # Run tests + build + sonar
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
         mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Ecommerce-Group-Project_Product-service 
       

      # Upload built jar
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: product-service
          path: target/product-service.jar

  publish:
    name: Publish to argocd
    needs: build
    runs-on: ubuntu-latest
    environment: production

    env:
      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      ACR_REGISTRY_NAME: ${{ vars.ACR_REGISTRY_NAME }}
      ACR_DOMAIN_NAME: ${{ vars.ACR_REGISTRY_NAME }}.azurecr.io
      REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}

      INFRA_REPO: 'Ecommerce-Group-Project/git-ops'
      MANIFEST_PATH: 'k8s/product_service/deployment.yaml'

    steps:

      # Check out source code
      - name: Checkout Code Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      # Download JAR produced by build job
      - name: Download JAR Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: product-service
          path: .

      # Move the file out of the auto-generated artifact folder if it nested it
      - name: Ensure JAR is in root
        run: |
          if [ -f "product-service/product-service.jar" ]; then
            mv product-service/product-service.jar ./product-service.jar
          fi
          echo "=== Verifying file location ==="
          ls -la
      # 1. Log in to Docker Hub securely
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


#      # Login to Azure
#      - name: Azure Login
#        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      # Login to Azure Container Registry
#      - name: Login to ACR
#        run: az acr login --name ${{ env.ACR_REGISTRY_NAME }}

      # Build and Push Docker Image
      - name: Build and Push Image
        id: build-image
        run: |
          IMAGE_URI="wicky2001/product_service:${{ github.sha }}"
  
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
  
          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

      # Checkout GitOps repository
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO }}
          path: gitops-repo

      # Update deployment manifest
      - name: Update Kubernetes Deployment Manifest
        run: |
          IMAGE_URI=${{ steps.build-image.outputs.image }}
  
          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' \
            -i gitops-repo/${{ env.MANIFEST_PATH }}

      # Commit & Push changes
      - name: Commit and Push Changes
        run: |
          cd gitops-repo
  
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
  
          git add ${{ env.MANIFEST_PATH }}
  
          git diff --cached --quiet || \
          git commit -m "ci: update product-service image tag to ${{ github.sha }}"
  
          git push origin main